name: Build Web

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - name: Get Flutter project dependencies
        run: flutter pub get
      - name: Run unit tests
        run: flutter test test/unit_test.dart
      - name: Run widget tests
        run: flutter test test/widget_test.dart
      - name: Analyze app's files
        run: flutter analyze lib/main.dart --no-fatal-warnings --no-fatal-infos
      - name: Build for web in release mode
        run: flutter build web --release lib/main.dart
      - name: Publish to GitHub Pages (doesn't work)
        uses: bluefireteam/flutter-gh-pages@v7 # fails because workflow permissions setting not allowed
        with:
          customArgs: "lib/main.dart"
